set(VCPKG_ENV_PASSTHROUGH "OT_ANDROID_PLATFORM")
set(VCPKG_ENV_PASSTHROUGH_UNTRACKED "EXTERNAL_QT_DIR;ANDROID_SDK_ROOT;ANDROID_NDK_HOME")

if(DEFINED ENV{OT_ANDROID_PLATFORM})
  message(STATUS "using $ENV{OT_ANDROID_PLATFORM} for ANDROID_PLATFORM")
  set(ANDROID_PLATFORM "$ENV{OT_ANDROID_PLATFORM}")
else()
  message(FATAL_ERROR "you must set OT_ANDROID_PLATFORM in the environment before using this triplet")
endif()

set(ANDROID_ABI "arm64-v8a")
set(ANDROID_STL "c++_shared")
set(ANDROID_SDK_ROOT "$ENV{ANDROID_SDK_ROOT}")

set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

if(PORT MATCHES "^qt")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
if(PORT MATCHES "openssl")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

set(VCPKG_CMAKE_SYSTEM_NAME Android)
set(VCPKG_MAKE_BUILD_TRIPLET "--host=aarch64-linux-android")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DANDROID_ABI=${ANDROID_ABI};-DANDROID_SDK_ROOT=${ANDROID_SDK_ROOT};-DANDROID_PLATFORM=${ANDROID_PLATFORM};-DANDROID_STL=${ANDROID_STL}")

include($ENV{ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake)
