set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(CMAKE_C_COMPILER "$ENV{VCINSTALLDIR}Tools/Llvm/$ENV{VSCMD_ARG_TGT_ARCH}/bin/clang-cl.exe")
set(CMAKE_CXX_COMPILER "$ENV{VCINSTALLDIR}Tools/Llvm/$ENV{VSCMD_ARG_TGT_ARCH}/bin/clang-cl.exe")
